name: ci

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: knpavankumar/k8s-job-cleaner-go:$(date +%s)
